export const GETNEWS_START="GETNEWS_START"
export const GETNEWS_SUCCESS="GETNEWS_SUCCESS"
export const GETNEWS_ERROR="GETNEWS_ERROR"

export const GETCATEGORYNEWS_START="GETCATEGORYNEWS_START"
export const GETCATEGORYNEWS_SUCCESS="GETCATEGORYNEWS_SUCCESS"
export const GETCATEGORYNEWS_ERROR="GETCETEGORYNEWS_ERROR"
